name: Continuous Integration

on: [pull_request]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install Dependencies
      run: npm install
    - name: Lint and Validate JSON Schema
      run: npm run lint
